### PR TITLE
#165599668 Add pagination to get bookmarks

### PR DESCRIPTION
**Pull request by fejiroofficial**
#### What does this PR do?
This PR is raised to:
- add pagination to get all bookmarks
- add author and category name to the response

#### Description of Task to be completed?
- add pagination to get all bookmarks
- add author and category name to the response
- fix failing tests

#### How should this be manually tested?
- clone the repo
- install postgress, node js and yarn
- run yarn install to install dependencies
- run yarn start:dev

#### What are the relevant pivotal tracker stories?
[#165599668](https://www.pivotaltracker.com/story/show/165599668 )

### CODE REVIEW

**Review by devdbrandy — APPROVED** [review]
✨ It looks good

**Review by aanchirinah — APPROVED** [review]
LGTM

**Comment by aanchirinah** [comment]
@fejiroofficial , Build failed

**Comment by fejiroofficial** [comment]
@aanchirinah Good morning! The build looks good to go.

**Pull request merged**
