### PR TITLE
#164198183 Social authentication

### PR DESCRIPTION
**Pull request by Andraquin**
#### What does this PR do?
It enables social authentication using facebook, twitter and google

#### Description of Task to be completed?
- write unit test
- write integration test
- install passport
- install passport strategy for facebook, twitter and google
- configure passport and passport strategies
- resolve conflicts

#### How should this be manually tested?
- Follow the steps below:
  - Run the following commands in your terminal
`git clone https://github.com/andela/apollo-ah-backend.git`
`cd apollo-ah-backend`
- Run `npm install` to install all dependencies.
- Create your own `.env` file using the `.env.example`
- Register or create your app on twitter developer, faceback developer and google developer site
- Paste the following code in the javascript file created
- Visit `api/v1/auth/facebook` to authenticate with facebook
- `api/v1/auth/twitter` to authenticate with twitter
- `api/v1/auth/google` to authenticate with google
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#164198183](https://www.pivotaltracker.com/story/show/164198183)
#### Screenshots (if appropriate)
facebook
google
twitter

#### Questions:

### CODE REVIEW

**Comment by aanchirinah** [comment]
@Andraquin , You have failing tests and builds

**Comment by jomadoye** [comment]
Hi @Andraquin If there's a Passport strategy for medium.com please add it.

**Comment by Andraquin** [comment]
> Nice work. Check, the eslinting, and your jsdoc in the controller, auth.js, then you could rename your controller to authController.js

@davdwhyte87 Thank you, I have attended to the above mentioned

**Comment by Andraquin** [comment]
> Hi @Andraquin If there's a Passport strategy for medium.com please add it.
> 
> cc @aanchirinah

Hi, @jomadoye there is no passport strategy for medium.com
cc @aanchirinah

**Comment by Andraquin** [comment]
> @Andraquin , You have failing tests and builds

@aanchirinah, I have it fixed now

**Pull request merged**
