### PR TITLE
Merge Staging into Master 

### PR DESCRIPTION
**Pull request by aanchirinah**
### Description
- After 2 sprints of building our backend for Author's haven.

### CODE REVIEW

**Comment by devdbrandy** [comment]
Hi @aanchirinah, the following PR #55 has addressed the issue. Kindly give your thought about it, thanks.

**Comment by devdbrandy** [comment]
@aanchirinah All checks have passed, except for one which is quite similar with the issue addressed here: [travis issue](https://github.com/travis-ci/travis-ci/issues/10018).

Screen Shot 2019-04-01 at 12 36 33 AM

I currently don't have travis installed locally, but I will be able to finalise a workaround when I get a stable network.

**Comment by devdbrandy** [comment]
@aanchirinah I have implemented the workaround and raised a PR on that: #56

**Comment by aanchirinah** [comment]
@devdbrandy , Your review is required ooo

**Pull request merged**
