### PR TITLE
#165634365 Resolve issue with user followers with minimal improvement

### PR DESCRIPTION
**Pull request by devdbrandy**
#### What does this PR do?

This provides a resolve for user followers where the request fails to retrieve all user followers

#### Description of Task to be completed?

- [x] Move followers endpoint to the top-most level
- [x] Validate profile resource by username 
- [x] Handle validation from middleware
- [x] Write test against resolve
- [x] Add user profile to followers payload

#### How should this be manually tested?

1. Run the following commands on terminal:

```bash
git clone -b bug/165634365/followers-bugfix --single-branch \
https://github.com/andela/apollo-ah-backend.git

cd apollo-ah-backend
cp .env.example .env

# To run test
cp .env.example .env.test

# Install package modules
npm install
```

2. Modify `.env.test` file with your db credentials

3. Run database migrations with `npm run migrate`

4. Run seeders with `npm run seed`

5. Run `npm run start:dev` to spin up the server.

#### Running test locally

Two npm scripts are available to run the test suite:

- `npm run mocha` or `npm run mocha:watch` - The later watches for any file changes and runs the full test suite (without code coverage)
- `npm test` - Performs a single full test suite run, including Istanbul code coverage reporting. Summary coverage reports are written to stdout, and detailed HTML reports are available in /coverage/index.html

**NOTE:** To run test locally, make sure to create `.env.test` file.

#### Any background context you want to provide?

n/a

#### What are the relevant pivotal tracker stories?

[#165634365](https://www.pivotaltracker.com/story/show/165634365)

#### Screenshots (if appropriate)

n/a

### CODE REVIEW

**Review by aanchirinah — APPROVED** [review]
LGTM

**Review by valenstical — APPROVED** [review]
LGTM

**Comment by aanchirinah** [comment]
@devdbrandy , some status checks are failing.

**Comment by devdbrandy** [comment]
@aanchirinah I have implemented the requested changes.

**Pull request merged**
